### ISSUE TITLE
v2.1.0 (Rebrand) release throwing a SIGSEGV

### ISSUE THREAD

**Issue by Tha14** [gillian-guide/GTAIVDowngradeUtilityWPF#2]
Trying to run the latest release(v2.1.0 (Rebrand)) crashes on my system upon launch. The regular 2.1.0 seems to run fine. GDB says that it's a SIGSEGV. Couldn't get more info in x64dbg so not much more I can provide at the moment(besides the 2 lines of log it writes before it crashes).

I am on windows 10 21H1, I believe that I have all .net versions including and below 8.0 installed.

LOG:
```
2024-04-02 07:15:05.7418|INFO|GTAIVDowngradeUtilityWPF.MainWindow| Initializing the main window...
2024-04-02 07:15:10.4721|INFO|GTAIVDowngradeUtilityWPF.MainWindow| Main window initialized!
```

PS: Thanks for the toolz!

**Comment by SandeMC** [comment]
No idea what causes this, but I'll revert it later today. Happy (late) April Fools!
