### ISSUE TITLE
Changing Graphic Settings Crashes the game.

### ISSUE THREAD

**Issue by two1212** [gillian-guide/GTAIVDowngradeUtilityWPF#5]
Changing Graphics settings like Resolution, Shadows, Reflections, Water Quality etc in-game causes a Crash.
Doesn't Crash while changing from Main Menu only after loading in-game. Doesn't matter if I use older saves or create a new one.

These are the setting used for downgrading from Steam build.
![Screenshot 2024-11-08 032503](https://github.com/user-attachments/assets/1c738841-dd54-4f65-97e3-f0ef55e5f6f1)

NOTE: Removing FusionFix-GFWL or using FusionFix-GFWLMin fixes the issue.
Using v1.2.0.43 of game with Downgrader v3.1.2.2 (Oct 3 Build)

ASI Loader's dumps and logs.
[CrashDumps.zip](https://github.com/user-attachments/files/17670037/CrashDumps.zip)

Edit: This seems to be an issue with FusionFix-GFWL but I don't know if I should open an issue there since I got this problem after using the Downgrader while I confirmed it to be a FusionFix problem through process of elimination. 

Should I open this issue in FusionFix-GFWL's repo and close it here?

**Comment by SandeMC** [comment]
i forgot to update my patches
